# Meta Data for SEO

metaautor = "ROKT GmbH - hallo@rokt.cloud"
metacopyright = "ROKT GmbH - hallo@rokt.cloud"

## Homepage
title = "ROKT"
titleSeparator = "-"
titleAddition = "into the cloud"
description = ""

## Open Graph
images = ["rokt_og.png"]
ogLocale = "de_CH"
titleHome = ""

## Twitter Cards
twitterSite = "@rokt_cloud"
twitterCreator = "@rokt_cloud"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "rokt_cloud"
schemaAuthor = "rokt_cloud"
schemaAuthorTwitter = "https://twitter.com/rokt_cloud"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/rokt_cloud/"
schemaAuthorGitHub = "https://github.com/rokt-cloud"
schemaLocale = "de-CH"
schemaLogo = "logo-rokt.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "rokt.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/rokt_cloud"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/rokt-cloud"

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "320"

# Footer
footer = '<a href="mailto:hallo@rokt.cloud">hallo@rokt.cloud</a>'

# Feed
copyRight = ""

# Alert
alert = false
alertDismissable = true
alertText = ""

# lazyimg
[lazyimg]
  resizer = "auto"
  renderer = "lqip-webp"

  # Resizer options:
  lqipSize = "120x Gaussian"
  maxSize = "1920x"
  responsiveSizes = [ "320x", "640x", "768x", "1024x", "1366x", "1600x", "1920x" ]
  resizeOptions = "Lanczos q95"

  # Renderer options:
  class = "img-fluid"
  # alt = ""
  noscript = true

  errorHandler = "warning"