# Meta Data for SEO

metaautor = "Tim&Koko AG - hallo@tim-koko.ch"
metacopyright = "Tim&Koko AG - hallo@tim-koko.ch"

## Homepage
title = "tim&koko"
titleSeparator = "-"
titleAddition = "into the cloud"
description = ""

## Open Graph
images = ["timkoko_og.png"]
ogLocale = "de_CH"
titleHome = ""

## Twitter Cards
twitterSite = "@tim_und_koko"
twitterCreator = "@rtim_und_koko"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "tim-koko"
schemaAuthor = "tim-koko"
schemaAuthorTwitter = "https://twitter.com/tim_und_koko"
schemaAuthorLinkedIn = "https://www.linkedin.com/company/tim-koko/"
schemaAuthorGitHub = "https://github.com/tim-koko"
schemaLocale = "de-CH"
schemaLogo = "logo-timkoko.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "timkoko_og.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/tim_und_koko"
schemaLinkedIn = "https://www.linkedin.com/company/tim-koko/"
schemaGitHub = "https://github.com/tim-koko"

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "320"

# Footer
footer = '<a href="mailto:hallo@tim-koko.ch">hallo@tim-koko.ch</a>'

# Feed
copyRight = ""

# Alert
alert = true
alertDismissable = true
alertText = ""

# lazyimg
[lazyimg]
  resizer = "auto"
  renderer = "lqip-webp"

  # Resizer options:
  lqipSize = "120x Gaussian"
  maxSize = "1920x"
  responsiveSizes = [ "320x", "640x", "768x", "1024x", "1366x", "1600x", "1920x" ]
  resizeOptions = "Lanczos q95"

  # Renderer options:
  class = "img-fluid"
  # alt = ""
  noscript = true

  errorHandler = "warning"