[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20.13.1"
  NPM_VERSION = "10.5.2"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.next]
  command = "npm run build"

[context.next.environment]
  HUGO_ENV = "next"

[[redirects]]
# redirect old blog post to new one
  from = "/blog/rokt-tim-koko/*"
  to = "/blog/tim-koko/"
  status = 301
  force = true
[[redirects]]
# redirect old en blog post to new one
  from = "/en/blog/rokt-tim-koko/*"
  to = "/en/blog/tim-koko/"
  status = 301
  force = true

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "connect-src * 'self';"